// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI93zV-EqOqGNo1QkU1dfg4XbGTm1VS_U',
    appId: '1:84643892834:web:e28989b30da5bb518e8b3b',
    messagingSenderId: '84643892834',
    projectId: 'voyage-be56a',
    authDomain: 'voyage-be56a.firebaseapp.com',
    storageBucket: 'voyage-be56a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ_jOrt2OmNAFubrxfiQoCGvXICViW8s4',
    appId: '1:84643892834:android:a8918b14746cf5848e8b3b',
    messagingSenderId: '84643892834',
    projectId: 'voyage-be56a',
    storageBucket: 'voyage-be56a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3SVz4L7fBqmVfxT4NjVeO5DOt_YVYk1M',
    appId: '1:84643892834:ios:c7970926da8ee8db8e8b3b',
    messagingSenderId: '84643892834',
    projectId: 'voyage-be56a',
    storageBucket: 'voyage-be56a.appspot.com',
    iosBundleId: 'com.example.voyage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3SVz4L7fBqmVfxT4NjVeO5DOt_YVYk1M',
    appId: '1:84643892834:ios:c7970926da8ee8db8e8b3b',
    messagingSenderId: '84643892834',
    projectId: 'voyage-be56a',
    storageBucket: 'voyage-be56a.appspot.com',
    iosBundleId: 'com.example.voyage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBI93zV-EqOqGNo1QkU1dfg4XbGTm1VS_U',
    appId: '1:84643892834:web:bd9cc2f9d83c862b8e8b3b',
    messagingSenderId: '84643892834',
    projectId: 'voyage-be56a',
    authDomain: 'voyage-be56a.firebaseapp.com',
    storageBucket: 'voyage-be56a.appspot.com',
  );
}
